### ISSUE TITLE
ArithmeticException specification missing for MonetaryAmount abs() and negate()

### ISSUE THREAD

**Issue by marschall** [JavaMoney/jsr354-api#103]
The methods `MonetaryAmount#abs()` and `MonetaryAmount#negate()` currently do no specify any exceptions. However their implementations in `FastMoney` throw an `ArithmeticException` if the result exceeds the numeric capabilities of this implementation class.
We believe this behavior makes sense and is in line with other methods on `MonetaryAmount`. Therefore we would like to see the specification of the `#abs()` and `#negate()` methods updated to specify this behavior.

**Comment by stokito** [comment]
the ArifmaticException is RuntimeException, so not needed to be declared in method’s throws list. Are we talking about update of javadoc?
It might be even better to throw MonetaryException instead because AE is very low level.

**Comment by marschall** [comment]
We are just talking about the Javadoc and the "contract" specified in the Javadoc laying out when an implementation is allowed or even required to throw which exceptions.

The request for `ArithmeticException` rather than `MonetaryException` comes from the fact that the class comments of  `MonetaryAmount` and the method comment of methods like `#add` define an `ArithmeticException` should be thrown in the result exceeds the numeric capabilities of this implementation class.

**Comment by keilw** [comment]
I would also rather throw a `MonetaryException` where possible and an underlying exception like AE as cause.

**Comment by marschall** [comment]
@keilw this would directly violate the specification in the class comment of `MonetaryAmount` and be inconsistent with the specification in other method of `MonetaryAmount` like `#add`

**Comment by keilw** [comment]
I'm afraid, `MonetaryAmount` is a little inconsistent because every comparison method `@throws MonetaryException if the amount's currency is not equal to the currency of this instance.` while most other operations throw an `ArithmeticException`. However, because the closest equivalent in `BigDecimal `(abs() without argument) does not declare the exception there either, I would not do it here, `MonetaryAmount` tries to be as consistent with `BigDecimal` as possible. Same for `negate()`.

**Comment by marschall** [comment]
That's what I mean the RI currently throws `ArithmeticException` for `#abs()` and `#negate()`. Methods like `#add(MonetaryAmount)` and `#subtract(MonetaryAmount)` explicitly allows this as per Javadoc. `#abs()` and `#negate()` do not explicitly mention this.
All I want it the Javadoc of `#abs()` and `#negate()` to explicitly allow the behavior of the RI.

**Comment by keilw** [comment]
Can you provide a Unit test to demonstrate that? We may have to fix that, the no-op abs() or negate() should be consistent with `BigDecimal`.

**Comment by marschall** [comment]
Here's a test that make the RI throw `ArithmeticException` for `#abs()` and `#negate()`.

```java
    FastMoney money = FastMoney.of(BigDecimal.valueOf(Long.MIN_VALUE, 5), EUR);
    money.abs();
    money.negate();
```

Again I believe this behavior is correct. I would just like to see the Javadoc of `#abs()` and `#negate()` be changed to allow this.

**Comment by keilw** [comment]
It's an implementation detail and sort of unwanted side-effect of `FastMoney` calling some new Java 8 methods like `Math.negateExact(this.number)` in the new constructor. I don't think you'll find it in `Money` because it makes proper use of `this.number.negate()` in the same situation. If some implementation make calls that cause an `ArithmeticException` or other `RuntimeException`, these are implementation details and have nothing to do with the API contract so it does not have to go into the JavaDoc. The other method refers to the context, there it is OK just like in `BigDecimal`.

**Comment by marschall** [comment]
> these are implementation details and have nothing to do with the API contract so it does not have to go into the JavaDoc

That's not what the API currently says. The class comment of `MonetaryAmount` currently already mentions that throwing `ArithmeticException` is preferred and some methods `#add` explicitly mention this but  `#abs()` and `#negate()` do not.

**Comment by keilw** [comment]
Yes because you won't find an `ArithmeticException` thrown by `Money`, so the class comment is sufficient. The makers of the JDK do not force it or mention it in abs(), therefore as not all implementations would even throw it, the class level recommendations (if the situation arises) seems enough.
We have far more critical issues in the implementations to solve.
