### ISSUE TITLE
Latest Version not working with Java8

### ISSUE THREAD

**Issue by MALPI** [JavaMoney/jsr354-api#82]
Hi there,

latest version of `javax.money:money-api:1.0.2` cannot be used in Java 8 environment anymore. Is this done by intention?

`Caused by: java.lang.UnsupportedClassVersionError: javax/money/MonetaryAmount has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

Best

**Comment by keilw** [comment]
@MALPI Why did you close it? Did it work with another version or this particular one?

**Comment by MALPI** [comment]
@keilw I closed it after checking the ri Readme and assumed this is intended:

**Comment by keilw** [comment]
Are you using it with OSGi?

**Comment by MALPI** [comment]
No it doesnt

**Comment by c0dehunter** [comment]
Soooo..  any news?

**Comment by keilw** [comment]
Because  `javax.money:money-api:1.0.2` is not the latest version, can you please confirm that you tried 
`javax.money:money-api:1.0.3` already? 

The mentioned error has been fixed with 1.0.3, I saw the OSGi META-INF could still refer to 9, but that will not affect anyone outside an OSGi container. It has not even been verified to be a problem in OSGi, but there was another ticket for an RI suggesting it might need addressing OSGi.

**Comment by keilw** [comment]
@MALPI @c0dehunter Did you try with 1.0.3?

**Comment by keilw** [comment]
We assume the problem to be fixed with the 1.0.3 Service Release. @MALPI @c0dehunter please if you still face any issues, let us know, we (the new Maintenance Leads) plan an official MR1 of JSR 354 relatively soon.

**Comment by dleangen** [comment]
I am not able to run in OSGi because of this problem.

I am not able to find a binary of 1.0.4 to verify that it works.

I am unable to build on my Mac using java8.

What should I do?
